name: food_app_home_task_eldad
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  logger: ^2.2.0
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0' # required dart >=2.19

flutter:

  uses-material-design: true
